version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
